CREATE TABLE IF NOT EXISTS seminar_applications (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    program         TEXT,
    fio_latin       TEXT NOT NULL,
    fio_ru          TEXT,
    birth_date      TEXT,
    gender          TEXT,
    country         TEXT,
    city            TEXT,
    arrival         TEXT,
    citizenship     TEXT,
    all_citizenships TEXT,
    phone           TEXT,
    email           TEXT,
    messenger       JSONB,
    messenger_link  TEXT,
    messenger_other TEXT,
    org_name        TEXT,
    org_spec        TEXT,
    org_location    TEXT,
    position        TEXT,
    audience        JSONB,
    audience_other  TEXT,
    stream          TEXT,
    how_learned     TEXT,
    intl_programs   TEXT,
    intl_details    TEXT,
    ru_programs     TEXT,
    ru_details      TEXT,
    why             TEXT,
    coop            TEXT,
    mentor          TEXT,
    directions      JSONB,
    directions_other TEXT,
    address         TEXT,
    passport_series TEXT,
    passport_number TEXT,
    passport_date   TEXT,
    passport_issued TEXT,
    portfolio_path  TEXT,
    consent_path    TEXT,
    payload_raw     JSONB
);

CREATE INDEX IF NOT EXISTS seminar_applications_email_idx
    ON seminar_applications (email);
CREATE INDEX IF NOT EXISTS seminar_applications_created_idx
    ON seminar_applications (created_at DESC);
